---
- name: Copy file to hosts
  hosts: mypc
  become: yes

  vars:
    source_file: /etc/ansible/tardeb/Zoiper5_5.4.12_x86_64.deb
    destin_file: /tmp/

  tasks:
  - name: Copy file1
    copy: src={{ source_file }} dest={{ destin_file }} mode=0777

  - name: Install a .deb package from the internet
    apt:
      deb: /tmp/Zoiper5_5.4.12_x86_64.deb
